// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ランタイム側（src/lib/prisma.ts）と同じフォールバック値を使う。
    // .env で DATABASE_URL を省略しても prisma CLI（db push / migrate 等）が
    // 動くようにするため。
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
